### PR TITLE
Grocery Store

### PR DESCRIPTION
**Pull request by kariabancroft**
Too general?

### CODE REVIEW

**Comment by CheezItMan** [comment]
Is the goal for the students to look at the grocery store problem and decide the classes & methods they would use?  As written this is going to give them a lot of decisions to make, and some will founder, unsure about what to do, but that's not necessarily a bad thing.  I think it's close to time for us to give more ambiguous problems for them to design solutions for.  They need some practice prior to bEtsy.

I think given this we'll see some solutions with students creating isle classes and others without.  We'll definitely see a variety of solutions here.  

Too late at this time around, but next cohort I think giving them time to talk about their designs with a seatsquad member (not the whole class) before the holiday would be a good idea to help them think it through.  Maybe we could have the seatsquads write user-stories, introducing that earlier.

ok </ramble>

**Comment by kariabancroft** [comment]
@CheezItMan I think the idea is focusing on the design more than "implement this code that we're telling you to implement". It's optional, so I want to make it as open-ended as possible. That being said, I guess I need @droberts-ada buy-in that this accomplishes what he is looking for.

**Comment by Hamled** [comment]
I agree with @CheezItMan that there's a lot of room to make decisions around a more advanced model of the grocery store. However, I do worry that just specifying the two sets of minimum requirements might indicate to students that shouldn't try to implement any additional classes, since that was largely how things worked out with Ride Share.

Perhaps we could give a short narrative example of a hypothetical user of this codebase, to more fully represent the design space without being too specific or prescriptive about which aspects should be considered for implementation.

**Comment by kariabancroft** [comment]
@Hamled Sure! I really like the idea, but have no idea how to do that. I have done my own implementation, but I feel that explaining one option immediately limits design opportunities. If you have an idea I'd love to see how to accomplish what you are describing as not "too specific or prescriptive"

**Comment by droberts-sea** [comment]
I think I like this. We don't explicitly tell them there should be 2 classes, but having descriptions of 2 things is a pretty big hint. I think that's right about where I'd want it.

One thing I'd like to see more of is interesting business logic - right now, it seems like we're basically just asking them to implement the relations. Maybe something like, given a list of products, calculate the total price and the amount saved via the discount? That might end up being a whole different class (customer order or something like that), which has `calculate_price`, `calculate_savings` and `checkout` methods.

**Comment by Hamled** [comment]
@kariabancroft I added what I think might be a useful narrative example of a terminal-based program that covers the listed minimum behavior, and has a few hooks for extended functionality that hopefully would encourage students to consider more implementation possibilities.

**Comment by droberts-sea** [comment]
Added a few things:
- Requirements for interesting business logic
- Advice on workflow
- Testing tips

Since this is going to be most useful for our weakest students, reminding them to focus on the fundamentals is probably worthwhile.

Kari told me I should just merge this when I had made these changes, so I am going to merge it right now!

**Pull request merged**
